global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'http-server'
    static_configs:
      - targets: ['webserver:8080']
        labels:
          service: 'http-server'
          environment: 'docker'
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
